### ISSUE TITLE
SVG

### ISSUE THREAD

**Issue by Kipperlenny** [Blobfolio/blob-mimes#4]
I just created a logo.svg with Adobe Illustrator, and cannot upload it - bug?

> ======================================================================
>                                 RESULT                                
> ======================================================================
> The following error(s) were found:
> — WordPress will not process this file based on its name.
> — The file type is not allowed.
> 
> 
> ======================================================================
>                                 TESTS                                 
> ======================================================================
> 
> 
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
>                               WORDPRESS                               
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
> PASS:          FALSE
> TEST:          [ext] FALSE
>                [type] FALSE
> RESULT:        [error] WordPress will not process this
>                file based on its name.
> 
> 
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
>                                FILEINFO                               
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
> PASS:          FALSE
> TEST:          [type] image/svg+xml
>                [match alias] TRUE
>                [allowed explicit] FALSE
>                [allowed alias] FALSE
> RESULT:        [error] The file type is not allowed.
> 
> 
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
>                               BLOB-MIMES                              
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
> PASS:          FALSE
> TEST:          [name] logo.svg
>                [type] FALSE
>                [ext] FALSE
>                [renamed] FALSE
> RESULT:        [error] The file type is not allowed.
> 
> 
> ======================================================================
>                              ENVIRONMENT                              
> ======================================================================
> 
> 
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
>                               WORDPRESS                               
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
> VERSION:       4.8
> PLUGINS:       blob-mimes [0.6.1]
>                iwp-client [1.6.4.2]
>                qtranslate [3.4.6.8]
>                wordfence [6.3.14]
> THEME:         Divi-child [3.0.44.1500823063]
> 
> 
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
>                                  PHP                                  
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
> VERSION:       5.6.30-0+deb8u1
> OS:            Linux s2 3.16.0-4-amd64 #1 SMP Debian
>                3.16.43-2+deb8u2 (2017-06-26) x86_64
> EXTENSIONS:    Core; PDO; Phar; Reflection; SPL;
>                SimpleXML; Zend OPcache; apc; apcu; bcmath; bz2;
>                calendar; cgi-fcgi; ctype; curl; date; dba; dom; ereg;
>                exif; fileinfo; filter; ftp; gd; gettext; hash; iconv;
>                imagick; imap; intl; json; libxml; mbstring; mcrypt;
>                memcache; memcached; mhash; mysql; mysqli; openssl;
>                pcntl; pcre; pdo_mysql; pdo_sqlite; posix; pspell;
>                readline; recode; session; shmop; snmp; soap; sockets;
>                sqlite3; standard; sysvmsg; sysvsem; sysvshm; tidy;
>                tokenizer; wddx; xml; xmlreader; xmlrpc; xmlwriter;
>                xsl; zip; zlib

**Comment by joshstoik1** [comment]
Thanks for the info!

For security reasons, WordPress does not allow SVG file uploads by default. But it looks like your server is correctly identifying the file type otherwise, so that's good.

In order to upload SVG files, you'll need to add them to your site's upload type "whitelist". Your site is using a custom theme, right? If so, you can put the following code somewhere in that theme's  `functions.php` file:

```php
/**
 * Allow SVG File Uploads
 *
 * @param array $existing_mimes MIMEs.
 * @return array MIMEs.
 */
function custom_svg_upload_mimes ($existing_mimes=array()) {
	$existing_mimes['svg'] = 'image/svg+xml';
	return $existing_mimes;
}
add_filter('upload_mimes', 'custom_svg_upload_mimes');
```

If you would rather enable SVG uploads site-wide, regardless of theme, the simplest approach is to make a quickie "must-use" plugin. If there isn't already a directory called `mu-plugins` in your `wp-content/` path (e.g. the same place you'd find the regular `plugins` folder), make one. Then add the above code to a new PHP file, call it something like `upload-svg.php`, and throw it in the `mu-plugins` folder (just remember to add a `<?php` to the top of that file). WordPress loads all top-level PHP files inside the `mu-plugins` folder during boot, so nothing else is needed. If you ever need to undo the permission change, just delete the file.

**Comment by Kipperlenny** [comment]
Thank you!

**Comment by joshstoik1** [comment]
Sure, no problem! Thank you for taking the time to reach out. MIMEs is a cat-and-mouse game that definitely needs user feedback, so even though the issue here was WP itself, your effort is appreciated.

FYI, `Lord of the Files` gives uploaded SVGs a good scrubbing to help make sure they are safe for inclusion on a web site (it is crazy just how many ways an SVG can be evil!). So A), be sure you keep this plugin enabled so long as you're allowing SVGs, but also B) if you run into issues where an SVG file is "broken" after being uploaded, let me know.
