### ISSUE TITLE
csv support

### ISSUE THREAD

**Issue by mvrhov** [Blobfolio/blob-mimes#5]
```
======================================================================
                                RESULT                                
======================================================================
The following error(s) were found:
— WordPress will not process this file based on its name.
— The file type is not allowed.


======================================================================
                                TESTS                                 
======================================================================


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
                              WORDPRESS                               
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
PASS:          FALSE
TEST:          [ext] FALSE
               [type] FALSE
RESULT:        [error] WordPress will not process this
               file based on its name.


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
                               FILEINFO                               
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
PASS:          TRUE
TEST:          [type] text/plain
               [match alias] TRUE
               [allowed explicit] TRUE
               [allowed alias] TRUE
RESULT:        [pass] The file type and extension are both allowed.


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
                              BLOB-MIMES                              
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
PASS:          FALSE
TEST:          [name]
               affiliate-wp-export-referrals-08-11-2017-empty.csv
               [type] FALSE
               [ext] FALSE
               [renamed] FALSE
RESULT:        [error] The file type is not allowed.


======================================================================
                             ENVIRONMENT                              
======================================================================


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
                              WORDPRESS                               
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
VERSION:       4.8.1
```

**Comment by joshstoik1** [comment]
Are CSV files enabled for your environment? They should be by default, but the debug snippet you provided shows the basic name-based check failing. Regardless of the true nature of the file, the WORDPRESS check at the top should return:
```PASS:          TRUE
TEST:          [ext] csv
               [type] text/csv
RESULT:        [pass] The file extension is allowed.
```

Have you been able to upload other CSVs? I wonder if there is something hidden in that particular file's name, like whitespace, causing the primitive name-based check WordPress relies on to fail. Something like "...-empty.csv " rather than "...-empty.csv".

**Comment by mvrhov** [comment]
What do you mean by "Are CSV files enabled for your environment?"
This is an empty file with just a header line.. However even the full one does not succeed.

**Comment by joshstoik1** [comment]
WordPress restricts what kinds of files can be uploaded based on their name, specifically based on the extension at the end. By default, ".csv" files are allowed, but file types can be added to or removed from this list programmatically by hooking into the [upload_mimes](https://codex.wordpress.org/Plugin_API/Filter_Reference/upload_mimes) filter.

According to the debug information you first posted, WordPress rejected the file based on its name. I asked if you had been able to upload other CSV files because it is unusual that a theme or plugin would have removed support for that type of file. It would make more sense that the file name in this one case accidentally contains something it shouldn't, like whitespace, which might prevent WP from correctly identifying it.

Here is a simple test: Download [this test file](https://gist.githubusercontent.com/secretsquirrel/5113b1641be4f84f64d1/raw/81e103bea2d3554e4a90590b6a4f9f5d31f6ce18/test.csv) (just press `CTRL+s` to save it, leave the name as-is) and then try to upload it to WordPress.

If that test file works, then there is no problem with CSV files in general; there is probably something wrong with the file names containing your affiliate info. If this is the case, I recommend trying to open the CSV in a program like LibreOffice or Excel and using the Save-As feature to make a copy with a simpler name.

But if the test file is also rejected, then something in your WP installation is preventing CSV uploads. The most likely culprit is a plugin (particularly if you are using any plugins to add or remove allowed file types), though it may also be a theme. I recommend temporarily de-activating any file- or admin-related plugins (including `Lord of the Files`) one at a time to try to identify the source of the trouble.

If all else fails, you can use a text editor to save the following code to `wp-content/mu-plugins/csv-uploads.php` to enable CSV uploads (you might have to create the `mu-plugins` directory if it does not already exist):

```php
<?php

/**
 * Allow CSV Uploads
 *
 * @param array $existing_mimes MIMEs.
 * @return array MIMEs.
 */
function csv_upload_mimes ($existing_mimes=array()) {
	$existing_mimes['csv'] = 'text/csv';
	return $existing_mimes;
}
add_filter('upload_mimes', 'csv_upload_mimes', 999);
```

**Comment by mvrhov** [comment]
Will try this tomorrow but FYI. I had tried with the code above in my child theme and it didn't make any difference.

**Comment by joshstoik1** [comment]
If a plugin or theme is messing with the `upload_mimes` list, a function like the one I shared before will only work if it runs *after* the plugin's function. To that end, you could try changing `999` to `PHP_INT_MAX`.

If there are problems with the parent or child theme, placing that code inside its own file in the `mu-plugins` directory as I suggested might help. WordPress will automatically parse any code found in top-level PHP files within that directory, independent of any themes or plugins being used by the site. In general, these sorts of changes are better made there than in a child theme.

**Comment by mvrhov** [comment]
Hm. It seems that the function it didn't work with default priority e.g 1. Which I have tried first as I said yesterday. Now that the priority is 10, or your suggested 999 the upload succeeds.

WP really fu*ed up this one. Thanks for help.
