### ISSUE TITLE
json files

### ISSUE THREAD

**Issue by joyously** [Blobfolio/blob-mimes#7]
`json` isn't in the WP whitelist. So, with nothing special added, a json file won't upload. Using blob-mimes, it says 
```
+-------------+
|  WORDPRESS  |
+-------------+
PASS:          FALSE
TEST:          [ext] FALSE
               [type] FALSE
RESULT:        [error] WordPress will not process this file based on its name.

+------------+
|  FILEINFO  |
+------------+
PASS:          TRUE
TEST:          [type] text/html
               [match alias] FALSE
               [allowed explicit] TRUE
               [allowed alias] TRUE
RESULT:        [warning] The file extension does not match the type, however the type is allowed.

+----------------------+
|  BLOB-MIMES (0.8.9)  |
+----------------------+
PASS:          FALSE
TEST:          [name] package.json
               [type] FALSE
               [ext] FALSE
               [renamed] FALSE
RESULT:        [error] The file type is not allowed.
```

But if I add a filter to add the json mime type (I used 'application/json'), then blob-mimes is telling me that it will be renamed to htm.
```
+-------------+
|  WORDPRESS  |
+-------------+
PASS:          TRUE
TEST:          [ext] json
               [type] application/json
RESULT:        [pass] The file extension is allowed.

+------------+
|  FILEINFO  |
+------------+
PASS:          TRUE
TEST:          [type] text/html
               [match alias] FALSE
               [allowed explicit] TRUE
               [allowed alias] TRUE
RESULT:        [warning] The file extension does not match the type, however the type is allowed.

+----------------------+
|  BLOB-MIMES (0.8.9)  |
+----------------------+
PASS:          TRUE
TEST:          [name] package.htm
               [type] text/html
               [ext] htm
               [renamed] TRUE
RESULT:        [warning] The file extension does not match the type; it will be renamed.
```

Do I need to use a text mime-type?

**Comment by joshstoik1** [comment]
> +------------+
> |  FILEINFO  |
> +------------+
> TEST:          [type] text/html

Hmm. That is an oddly specific mistake for `fileinfo.so` to make. Most systems opt for the less declarative `text/plain` non-type type when faced with a random text file.

Out of curiosity, does that JSON file contain anything HTML-looking, like markup-in-a-string like `["<div>","Hello World","<\/div>"…]` or similar? If it doesn't contain anything particularly sensitive, would you mind throwing up a [pastebin](https://pastebin.com/) link or emailing me a copy? It would be interesting to see if the results can be replicated under different PHP configurations and environments.

Another useful test: if you were to upload a very simple JSON file, like one containing `[1,2,3]` or `{"foo":"bar"}`, does `fileinfo.so` still think they're HTML?

And one last question: would you mind sharing your PHP version and Linux distribution (or Windows or Mac if that's how you roll…)? As eluded to earlier, this sort of thing varies by environment, so those two pieces of information would help me replicate the results.

Thank you very much!

I have a few ideas about how to work around this particular issue in `Lord of the Files`, but your feedback will help determine which solution we go with. :smile: 

> Do I need to use a text mime-type?

No, you should always use the correct MIME type — `application/json` in this case — as WordPress will ultimately store files that way in the database, which could impact what WordPress does with them or how your server serves them.

**Comment by joyously** [comment]
I don't know what's in the file (I haven't looked and just chose one from a repo I had open). 
I was using this file: https://github.com/mavoweb/plugins/blob/master/package.json
on my Ubuntu Studio 16.04 xampp setup for PHP 5.5.15. That test was on WP 4.7.12. Switching to WP 5.0.3 on the same xampp didn't change the result (shall I say obviously?), but when I tried your test of using only `{"foo":"bar"}` then fileinfo gave the type as text/plain.

**Comment by joshstoik1** [comment]
Thanks @joyously!

Do you have FTP access to your site?

If so, would you mind grabbing https://raw.githubusercontent.com/Blobfolio/blob-mimes/master/wp/lib/blobfolio/wp/bm/mime.php and uploading it to `[path-to-your-plugins-directory]/blob-mimes/lib/blobfolio/wp/bm/mime.php` and then retry the file validation tool on the `package.json` file?

I added a surgical workaround for sites that whitelist `application/json` as a type. If `fileinfo.so` thinks a JSON file is anything other than `application/json`, the plugin will simply try to decode it, and if that works, it will ignore `fileinfo.so`'s result entirely.

That workaround seems to work on my test servers, but my servers were wrong in different ways from yours, so I'd feel better knowing it fixes things for you too before pushing a new release of the plugin. :smile:

**Comment by joyously** [comment]
OK, something's not quite right.
If I don't add my filter to allow json, your code does the right thing. But I need my filter to allow json, and that way, it gets renamed.

Without filter:
```
+-------------+
|  WORDPRESS  |
+-------------+
PASS:          FALSE
TEST:          [ext] FALSE
               [type] FALSE
RESULT:        [error] WordPress will not process this
               file based on its name.

+------------+
|  FILEINFO  |
+------------+
PASS:          TRUE
TEST:          [type] text/html
               [match alias] FALSE
               [allowed explicit] TRUE
               [allowed alias] TRUE
RESULT:        [warning] The file extension does not
               match the type, however the type is allowed.

+----------------------+
|  BLOB-MIMES (0.8.9)  |
+----------------------+
PASS:          FALSE
TEST:          [name] package.json
               [type] FALSE
               [ext] FALSE
               [renamed] FALSE
RESULT:        [error] The file type is not allowed.
```

With filter:
```
+-------------+
|  WORDPRESS  |
+-------------+
PASS:          TRUE
TEST:          [ext] json
               [type] application/json
RESULT:        [pass] The file extension is allowed.

+------------+
|  FILEINFO  |
+------------+
PASS:          TRUE
TEST:          [type] text/html
               [match alias] FALSE
               [allowed explicit] TRUE
               [allowed alias] TRUE
RESULT:        [warning] The file extension does not
               match the type, however the type is allowed.

+----------------------+
|  BLOB-MIMES (0.8.9)  |
+----------------------+
PASS:          TRUE
TEST:          [name] package.htm
               [type] text/html
               [ext] htm
               [renamed] TRUE
RESULT:        [warning] The file extension does not
               match the type; it will be renamed.
```

**Comment by joshstoik1** [comment]
Thanks for testing!

You will always need to keep the `upload_mimes` filter in place to whitelist JSON files. `Lord of the Files` doesn't make any changes to _allowed_ file types; it just helps WordPress be a little less stupid when checking to see which type of file a file is. (The WP Core will pretty much always get this wrong, especially for types that are not whitelisted by default.)

That results from your second test (with the filter in place) mirror the original plugin behaviors, so either the workaround code is not running at all, or the file you're uploading really isn't valid JSON.

This might seem like a silly question, but when you grabbed https://github.com/mavoweb/plugins/blob/master/package.json for testing, did you download that URL directly, or did you click the [Raw](https://github.com/mavoweb/plugins/raw/master/package.json) tab and download the file from there?

If you open the downloaded file in a text editor, the very first thing you should see is a `{`. If you happened to download the Github page by mistake, you'd instead see something like `<!DOCTYPE html>`. The latter _is_ HTML, so that would explain why the server is saying what it's saying, and also why it keeps saying it even with the plugin workaround. (I've certainly done this before;  I'm pretty sure everyone has at one time or another. Haha.)

If the `package.json` file you're using is the right, raw JSON file, then that means something in my workaround isn't triggering for you. The inner logic of that workaround is pretty simple, but has three possible points of failure:

```php
// 1. Requires the JSON PHP extension.
if (function_exists('json_decode')) {
	// 2. The temporary file has to be readable.
	$tmp = @file_get_contents($file);
	if (is_string($tmp) && $tmp) {
		// 3. json_decode() has to be able to parse it.
		$tmp2 = @json_decode($tmp, true);
		if (null !== $tmp2) {
			$real_mime = 'application/json';
		}
	}
}
```

If any of the above 3 parts fail, the plugin just goes on to evaluate things as it always has. We can pretty much discount the second in the list; if the file weren't readable or `file_get_contents()` were prohibited, lots of things would be broken. The third part is also unlikely as there are no "weird" characters in this file, and I can confirm `json_decode()` decodes it on my servers.

That basically just leaves (1): do you have the JSON PHP extension installed? That is usually installed by default, but perhaps it is missing? There should be a list of installed extensions at the end of the file validation output for reference.

Thank you again for taking all this time to help debug. I wish there were more consistency to this particular problem so I could tackle all the hard work on my own, but alas, no two systems act the same way. Haha.

**Comment by joyously** [comment]
You're so smart to see that I made a dumb mistake getting the json file from GitHub!  _I have never liked GitHub._
Yes, the file had HTML in it. Sorry! I just reran it with the correct contents, and it now types it as text/plain.
Everything looks good.
```
+-------------+
|  WORDPRESS  |
+-------------+
PASS:          TRUE
TEST:          [ext] json
               [type] application/json
RESULT:        [pass] The file extension is allowed.

+------------+
|  FILEINFO  |
+------------+
PASS:          TRUE
TEST:          [type] text/plain
               [match alias] TRUE
               [allowed explicit] TRUE
               [allowed alias] TRUE
RESULT:        [pass] The file type and extension are both allowed.

+----------------------+
|  BLOB-MIMES (0.8.9)  |
+----------------------+
PASS:          TRUE
TEST:          [name] package.json
               [type] application/json
               [ext] json
               [renamed] FALSE
RESULT:        [pass] The file type and extension are both allowed.
```

So since the fileinfo gives the wrong (but whitelisted) type, it should upload fine without the plugin, right?  And yet, it doesn't. I guess I'll have to do something like your plugin is doing to get it to work.

**Comment by joshstoik1** [comment]
Haha. Don't take it personally; I have made _exactly_ that same mistake before. And even though we were working from a faulty assumption in this thread, it did shed light on an opportunity to make LoTF's detection-correction a little more robust!

In terms of your upload life going forward, I would recommend you:
1. Keep the `upload_mimes` filter in place with the _correct_ media type for JSON files, i.e. `application/json`;
2. Keep `Lord of the Files` installed because the WordPress Core will probably never get file validation right, especially for types you've manually whitelisted;

But if you'd rather cut down on the number of plugins your site has to run — which  is totally understandable — you could get JSON files working natively by setting the `upload_mimes` type to `text/plain` (or whatever each server individually believes JSON files to be). The main thing to be aware of with this approach is you might need to use different values from one server to another, and the values might change from time to time because of PHP updates, etc., so it'll be a little cat-and-mouse.

Thanks again for all the back and forth!

**Comment by joyously** [comment]
> But if you'd rather cut down on the number of plugins your site has to run 

It's not that, it's that I'm writing a plugin to save data from a JS front-end, and json is the default type, although other types can be used (csv, yaml, images). So I have to handle it myself since the user won't have your plugin.
I don't have to use the WP upload functions, but I thought it would be smart to let WP do all the checking for me (capability combined with type). So much for that!

**Comment by joshstoik1** [comment]
Ug, yeah, you'll have to implement your own `wp_check_filetype_and_ext` filter callback in that case; I wouldn't trust WordPress to get it right on its own. :unamused: 

But if you run into any issues with that, I'd be more than happy to help; just drop me an email or something.
