### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by asha23** [Blobfolio/blob-mimes#8]
I have found this plugin to be extremely useful.

Do you know of any security implications when using the function `check_filetype_and_ext()` in admin.php of your plugin. 

I am using this function to allow for some obscure 3d Model file types to be uploaded .rvt, etc. Would I be correct in saying that this function essentially bypasses the WP core file type checking routine? Or am I way off the mark?

Could you possibly explain, when you have time, the difference between using this function and using the constant:

`define('ALLOW_UNFILTERED_UPLOADS', true);`

I'm quite new to WordPress mime types, but have been aware of the 3 year old problem with WordPress and uploading obscure file types for a while.

**Comment by joshstoik1** [comment]
Hi @asha23,

I'm glad you're finding the plugin useful!

It is important to note the `Lord of the Files` plugin _does not_ override or change which types of files are allowed to be uploaded to WordPress. (All regular WP filters and constants for opening or restricting uploads still apply.) Its job is more about helping WordPress make sure that the file being uploaded is actually the of the type WordPress thinks it is, or at least of a type that WordPress allows.

The problem with how WordPress currently handles file validation is that it partially relies on information provided by the underlying server environment, but does not take into account that that information varies widely across versions of PHP, operating systems, etc. As is, there are many cases where WordPress will accidentally forbid a legitimate file, and others where it will accidentally allow something malicious and bad. Haha.

To help address this, `Lord of the Files` acts as a sort of translator, using its knowledge of thousands of MIME aliases and type-specific workarounds to look at the server environment's evaluation in a clearer light.

To your question about the `ALLOW_UNFILTERED_UPLOADS` constant, you should probably never use that; it removes all file type checks entirely. Instead, you can hook into the [upload_mimes](https://developer.wordpress.org/reference/hooks/upload_mimes/) filter to explicitly whitelist the extra file types you're using.

`RVT`, unfortunately, isn't a "real" file type, so even with `Lord of the Files` installed, the site probably won't understand what it is based on its content. The `upload_mimes` filter requires you specify a type nonetheless, so I would recommend you set it to whatever type your server happens to believe it is (since that answer is what will be looked at during security checks). To find out what that value happens to be, you can go to Tools > Debug File Validation and do a test upload. The `FILEINFO [type]` value will be the type returned by the server. :)
