### ISSUE TITLE
PHP 7.1 is EOL on 1 Dec 2019

### ISSUE THREAD

**Issue by dac514** [Blobfolio/blob-mimes#9]
This commit broke the plugin for me.

https://github.com/Blobfolio/blob-mimes/commit/138ba7db9730143c450c3a14e805988b67d95af5#diff-e7115ebc7d0c0c7747ccd9671427e1f4R7

![image](https://user-images.githubusercontent.com/812192/67888746-0dc63a00-fb24-11e9-9ccc-2afc705e7508.png)

I understand, and appreciate, that this plugin doesn't support old versions of PHP. But that commit doesn't use any breaking PHP 7.2 features? More weirdly is that this plugin, in PHP instead of the README, is checking for PHP 5.4:

https://github.com/Blobfolio/blob-mimes/blob/138ba7db9730143c450c3a14e805988b67d95af5/wp/index.php#L52

Unfortunately, I didn't run into this until too late. 

My dev envrionment runs 7.3, but the machine I deploy to runs 7.1 which will not be updated until ~December when PHP 7.1 reaches EOL _(for realsies)_.

https://www.php.net/supported-versions.php

Can you switch the README back to PHP 7.1 for at least another month? For now I have downgraded to 0.9.5

**Comment by joshstoik1** [comment]
@connerbw,

Sorry about that. The WP repository minimum PHP requirements are kept purposefully high to encourage timely adoption, but the code itself doesn't yet contain anything that would break on older versions. (That will likely change once WordPress itself begins requiring 7.x.)

But you're right, `7.1` is still receiving extended support, so that should be OK for now. I went ahead and lowered the WP repo requirement for you. I'm not sure if your production environment will see that change right away or not, but it is already reflected at https://wordpress.org/plugins/blob-mimes/.

**Comment by dac514** [comment]
I think you will need to release a new version for someone like me to benefit:

https://plugins.trac.wordpress.org/browser/blob-mimes/tags/0.9.6/readme.txt

**Comment by joshstoik1** [comment]
I went ahead and pushed the November build `0.9.7` a couple days early. Are you able to deploy that version?

https://plugins.trac.wordpress.org/browser/blob-mimes/tags/0.9.7/readme.txt

**Comment by dac514** [comment]
Thanks. Works!
